# Generated by Django 3.1.3 on 2020-11-08 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('maturity', models.CharField(max_length=100)),
                ('lei', models.CharField(max_length=100)),
                ('legal_name', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['isin'],
            },
        ),
    ]
